[build]
  base = "Biblioteca Performr"
  publish = "Biblioteca Performr"
  functions = "Biblioteca Performr/netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
